---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-fallback
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-fallback
  template:
    metadata:
      labels:
        app: llm-fallback
    spec:
      containers:
        - name: simulator
          image: ghcr.io/llm-d/llm-d-inference-sim:latest
          args:
            - "--port"
            - "8001"
            - "--model"
            - "gpt-4"
            - "--mode"
            - "echo"
            - "--time-to-first-token"
            - "100"
            - "--inter-token-latency"
            - "20"
          ports:
            - containerPort: 8001
              name: http
          livenessProbe:
            httpGet:
              path: /v1/models
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/models
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: llm-fallback
  namespace: default
spec:
  selector:
    app: llm-fallback
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: llm-fallback-backend
  namespace: default
spec:
  schema:
    name: OpenAI
  backendRef:
    name: llm-fallback-backend-ref
    kind: Backend
    group: gateway.envoyproxy.io
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: llm-fallback-backend-ref
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: llm-fallback.default.svc.cluster.local
        port: 8001