name: Setup Prerequisites

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
        
    - name: Setup prerequisites
      run: |

        # Install Task

        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin/

        # Install kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        
        # Install kind
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.29.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/
        
        # Install helm
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        
        # Install jq (should already be available)
        sudo apt-get update
        sudo apt-get install -y jq
        
        # Verify installations
        echo "Tool versions:"
        kubectl version --client
        kind version
        helm version
        jq --version
        docker --version
        task --version

    - name: Free up disk space
      run: |
        docker system prune -af
        
    - name: Clean up existing Kind resources
      run: |
        echo "🧹 Cleaning up any existing Kind clusters and containers..."
        # Delete any existing kind clusters
        kind delete clusters --all || true