name: Validate Setup

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Verify Docker is running
      run: docker info
      
    - name: Run setup-all task
      run: task setup-all
      
    - name: Verify installation status
      run: |
        echo "=== Checking Task Status ==="
        task --status setup-all || echo "Setup-all not up-to-date (expected on first run)"
        
        echo "=== Checking Individual Task Status ==="
        task --status install-deps
        task --status create-cluster
        task --status install-envoy-gateway
        task --status install-envoy-ai-gateway
        
    - name: Run verification script
      run: task verify-installation
      
    - name: Check cluster status
      run: |
        echo "=== Cluster Info ==="
        kubectl cluster-info --kubeconfig=kubeconfig.yaml
        
        echo "=== Nodes ==="
        kubectl get nodes --kubeconfig=kubeconfig.yaml
        
        echo "=== Namespaces ==="
        kubectl get namespaces --kubeconfig=kubeconfig.yaml
        
    - name: Check Envoy Gateway status
      run: |
        echo "=== Envoy Gateway Pods ==="
        kubectl get pods -n envoy-gateway-system --kubeconfig=kubeconfig.yaml
        
        echo "=== Envoy Gateway Services ==="
        kubectl get services -n envoy-gateway-system --kubeconfig=kubeconfig.yaml
        
    - name: Check Envoy AI Gateway status
      run: |
        echo "=== Envoy AI Gateway Pods ==="
        kubectl get pods -n envoy-ai-gateway-system --kubeconfig=kubeconfig.yaml
        
        echo "=== Envoy AI Gateway Services ==="
        kubectl get services -n envoy-ai-gateway-system --kubeconfig=kubeconfig.yaml
        
    - name: Check quickstart application
      run: |
        echo "=== Quickstart Application ==="
        kubectl get pods -n default --kubeconfig=kubeconfig.yaml
        kubectl get services -n default --kubeconfig=kubeconfig.yaml
        kubectl get gateways -n default --kubeconfig=kubeconfig.yaml
        
    - name: Test basic functionality
      run: |
        echo "=== Testing Gateway Connectivity ==="
        # Wait for gateway to be ready
        kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=envoy-gateway -n envoy-gateway-system --timeout=300s --kubeconfig=kubeconfig.yaml
        
        # Get gateway service endpoint
        kubectl get service envoy-gateway-proxy -n envoy-gateway-system --kubeconfig=kubeconfig.yaml
        
    - name: Show logs on failure
      if: failure()
      run: |
        echo "=== Envoy Gateway Logs ==="
        kubectl logs -n envoy-gateway-system -l app.kubernetes.io/name=envoy-gateway --tail=100 --kubeconfig=kubeconfig.yaml || true
        
        echo "=== Envoy AI Gateway Logs ==="
        kubectl logs -n envoy-ai-gateway-system -l app.kubernetes.io/name=ai-gateway-controller --tail=100 --kubeconfig=kubeconfig.yaml || true
        
        echo "=== Kind Cluster Logs ==="
        kind export logs /tmp/kind-logs || true
        
    - name: Cleanup
      if: always()
      run: |
        echo "=== Cleanup ==="
        task cleanup || true
        docker system prune -f || true
